In [1]:
import pandas as pd

In [3]:
df_run1 = pd.read_json("../run1/run1_result.json",lines=True)
df_clean = pd.read_json("run2_result_cleaned.json",lines=True)
df_0 = df_run1[df_run1.topic==0]

In [4]:
print(df_run1.shape)
print(df_clean.shape)
print(df_0.shape)

(228275, 3)
(169680, 3)
(182145, 3)

In [5]:
df_0_dedup = df_0.drop_duplicates("cid",keep="first")
df_clean_dedup = df_clean.drop_duplicates("text",keep="first")

In [6]:
print(df_0_dedup.shape)
print(df_clean_dedup.shape)

(150777, 3)
(136123, 3)

In [7]:
df_clean_dedup
df_0_dedup

,cid,text,topic
0,bafyreihmqtib6dm76dgrnpiz5gdbzzcnskqpjovbi3owy...,Thank you hayleysmith.bsky.social latimes.com ...,0
1,bafyreihurshrofa7cck745p6mcp4cqfsr6rle5arwhedd...,Made the most of a weather-time-energy window ...,0
2,bafyreifst2eycalqgsrty4cyb2tbq5aqagy3yrvodq3vi...,thedailyshow.com of the Environmental Defense ...,0
3,bafyreic5q4z3jyudbkjj24t433h3giy6oicy6rv2ih4vz...,Can't wait for his demise. Never ever have I w...,0
4,bafyreibscp2vq5za5kbs2hw64jxpsu7of3jst2mldlwgl...,What aspect of it is art But also please answe...,0
...,...,...,...
228270,bafyreicyndhigsdfiuudid6g24httaubk4rwg4hxxolc4...,Protest at 999 Van Ness SF right now! Join us!...,0
228271,bafyreifv3syw4c2snz6q3hazm5qvm75sj52hn5evy74q7...,i went to easter mass today and surprisingly i...,0
228272,bafyreidyu6li3a3gdfgchsqfxabjly6sqcerbq52kyq3n...,We welcome all your scientists and of course f...,0
228273,bafyreicqydwevnilh2punkqkdjwdi5gzaquoxvbfphz5v...,Trump is such an amazing president for the env...,0
228274,bafyreihqkjhbgskvhnmvelzgxdrpdx76ko7gzas6lqgc4...,Thank you Alina! They are in the greenhouse no...,0

In [8]:
df_clean_dedup = df_clean_dedup[["text", "topic"]]
df_0_dedup = df_0_dedup[["cid","text"]]

In [9]:
df_clean_dedup
df_0_dedup

,cid,text
0,bafyreihmqtib6dm76dgrnpiz5gdbzzcnskqpjovbi3owy...,Thank you hayleysmith.bsky.social latimes.com ...
1,bafyreihurshrofa7cck745p6mcp4cqfsr6rle5arwhedd...,Made the most of a weather-time-energy window ...
2,bafyreifst2eycalqgsrty4cyb2tbq5aqagy3yrvodq3vi...,thedailyshow.com of the Environmental Defense ...
3,bafyreic5q4z3jyudbkjj24t433h3giy6oicy6rv2ih4vz...,Can't wait for his demise. Never ever have I w...
4,bafyreibscp2vq5za5kbs2hw64jxpsu7of3jst2mldlwgl...,What aspect of it is art But also please answe...
...,...,...
228270,bafyreicyndhigsdfiuudid6g24httaubk4rwg4hxxolc4...,Protest at 999 Van Ness SF right now! Join us!...
228271,bafyreifv3syw4c2snz6q3hazm5qvm75sj52hn5evy74q7...,i went to easter mass today and surprisingly i...
228272,bafyreidyu6li3a3gdfgchsqfxabjly6sqcerbq52kyq3n...,We welcome all your scientists and of course f...
228273,bafyreicqydwevnilh2punkqkdjwdi5gzaquoxvbfphz5v...,Trump is such an amazing president for the env...
228274,bafyreihqkjhbgskvhnmvelzgxdrpdx76ko7gzas6lqgc4...,Thank you Alina! They are in the greenhouse no...

In [10]:
df_full = df_clean_dedup.merge(df_0_dedup,on="text",how="left")

In [11]:
df_full.to_json("run2_result_clean_cid.json", orient= "records", lines=True)

In [14]:
from collections import Counter
Counter(df_full.topic)

Counter({-1: 73360,
         1: 4425,
         0: 4029,
         2: 3866,
         3: 3263,
         4: 2607,
         5: 2357,
         6: 1917,
         7: 1811,
         8: 1801,
         9: 1743,
         10: 1612,
         12: 1441,
         11: 1362,
         14: 1339,
         13: 1301,
         15: 1283,
         16: 1278,
         18: 1246,
         19: 1140,
         25: 991,
         27: 942,
         26: 916,
         29: 882,
         28: 881,
         30: 856,
         34: 850,
         31: 801,
         32: 788,
         33: 767,
         24: 728,
         40: 702,
         35: 697,
         38: 646,
         42: 618,
         41: 595,
         43: 591,
         44: 590,
         45: 530,
         50: 498,
         48: 482,
         37: 478,
         47: 460,
         53: 425,
         54: 394,
         56: 364,
         55: 359,
         59: 346,
         61: 326,
         60: 310,
         69: 309,
         49: 308,
         62: 301,
         64: 280,
         74: 280,
         71: 278,
         72: 259,
         79: 256,
         66: 251,
         83: 245,
         84: 240,
         81: 240,
         80: 239,
         68: 239,
         96: 237,
         93: 232,
         94: 232,
         86: 227,
         85: 226,
         77: 223,
         95: 213,
         87: 212,
         103: 207,
         98: 203,
         100: 197,
         97: 197,
         105: 196,
         99: 189,
         113: 187,
         110: 184,
         104: 179,
         107: 178,
         112: 174,
         114: 158,
         108: 141,
         102: 134,
         106: 116})